[package]
name = "doctest"
version = "0.1.0"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = { version = "3", default-features = false }
ammonia = "3"
iron = "0.6"
maud = { path = "../maud", features = ["actix-web", "iron", "rocket", "tide", "axum"] }
pulldown-cmark = "0.8"
rocket = { version = "0.4", default-features = false }
rouille = "3"
tide = { version = "0.16", default-features = false, features = ["h1-server"] }
tokio = { version = "1.9.0", features = ["rt", "macros", "rt-multi-thread"] }
axum = { version = "0.1.3", default-features = false }

[dependencies.async-std]
version = "1.9.0"
features = ["attributes"]

[lib]
path = "lib.rs"
